# Generated by Django 3.1.3 on 2020-11-10 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
