# Generated by Django 3.1.3 on 2020-11-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='exit', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
